apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-provision
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-db
        image: bitnami/postgresql:17
        command: [
          'sh',
          '-c',
          'until pg_isready -h {{ .Release.Name }}-postgresql -U postgres; do echo waiting for database; sleep 2; done'
        ]
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: postgres-password
      containers:
      - name: provision-db
        image: bitnami/postgresql:17
        command:
          - sh
          - -c
          - |
            psql -h {{ .Release.Name }}-postgresql -U postgres \
              -v DB_USER="$$DB_USER" \
              -v DB_PASSWORD="$$DB_PASSWORD" \
              -v DB_NAME="$$DB_NAME" \
              -f /scripts/init.sql
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: postgres-password
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-params
              key: DB_NAME
        volumeMounts:
        - name: init-script
          mountPath: /scripts
      volumes:
      - name: init-script
        configMap:
          name: {{ .Release.Name }}-db-init