apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep