apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": keep
type: Opaque
data:
  DB_USER: {{ printf "user_%s" (randAlphaNum 16 | lower) | b64enc | quote }}
  DB_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  API_KEY: {{ randAlphaNum 16 | b64enc | quote }}
